### ISSUE TITLE
Site title URL

### ISSUE THREAD

**Issue by chang48** [kura/hauntr#3]
Hello, thanks for creating the hauntr theme for pelican. I like its neat and clean design. I have an minor implementation issue of the theme I'd like to seek your input. It is about the site title's hyperlink. Normally the link is supposed to be the site's home address. However in my case, suppose I click into a post, the site title's URL stays as the post's address. The same happened to the site title for any page that is not the initial landing page. Did I miss anything in the settings? 

pelican: 4.8.0
pelican-themes: 0.2
My test site: https://chang48.github.io/

**Comment by chang48** [comment]
Okay, I think I found the cause, although not 100% sure.
In `base.html`, I changed 
`<h1 class="blog-title"><a href="{{ SITEURL }}">{{ SITENAME }}</a></h1>
            <h2 class="blog-description">`
to
`<h1 class="blog-title"><a href="{{ SITEURL }}/">{{ SITENAME }}</a></h1>
            <h2 class="blog-description">`
That it, a slash is added to the end of `{{ SITEURL }}`. After this minor change, the URL behaves as expected.

**Comment by kura** [comment]
Cool, good to know. Sorry for the delayed response, GitHub doesn't like sending me notifications for some reason.

**Comment by chang48** [comment]
Thanks, no worries. The slash is just a hack, I'm not sure if it really is the fix :) Anyhow, it seems to work.

**Comment by kura** [comment]
The correct fix is to do it in `pelicanconf.py`, e.g. `SITEURL = "https://kura.gg/"`

The template just uses a variable for the most flexibility, allowing the user to set it to whatever they wish without the template making any assumptions

**Comment by chang48** [comment]
> 

Got it. As you suggested, I removed the hack, put in the correct `SITEURL` which in my case is `/` and the site title URL worked as expected in any situation. Thanks for the solution!

**Comment by chang48** [comment]
There is an interesting twist. I set `SITEURL='/'` and tried to rebuild the site. But pelican would remove it:

`WARNING  Removed extraneous trailing slash from SITEURL.`

After a bit of Googling, this issue was raised before in multiple similar occasions:

- https://github.com/nairobilug/pelican-alchemy/pull/58
- https://github.com/getpelican/pelican/issues/1156
- https://github.com/arulrajnet/attila/pull/4

My pelican version is `4.8.0` and apparently the problem still exists. Anyhow, at least there is a way to move forward.

**Comment by kura** [comment]
Interesting. I've never set `SITEURL` to a relative value, only a domain name.

In that case I would suggest going back to a local checkout of the theme with a modified template. I do that with https://github.com/kura/kura.gg because I use a very modified version of my Eevee theme, I also have locally stored and modified plugins as part of the repo too.
It's not really much of a hack, it's nice to be able to override things like that. You can definitely safely do it with Hauntr because I haven't modified that theme in years and have no plans to do so in the near future.

**Comment by chang48** [comment]
Thanks! I'll follow through. Really appreciate your input.

**Comment by kura** [comment]
You're welcome. Good luck. 😊
